# Numpy: Numerical Python

*Chinellato Diego - TPSIT*

*ITTS V. Volterra*

*A.S. 2022/2023*

http://www.numpy.org/

**NumPy** stands for **Numerical Python**.

NumPy is a fundamental package for efficient scientific and numerical computing.

It provides:
- efficient methods for managing arrays and matrices, and operations on them
- several mathematical functions (variance, standard deviation, cumulative sum, ...)
- other: fitting a polynomial, finding the minimum of a function, Fast Fourier Transform, etc.

This notebook is based on Numpy's absolute basics tutorial: https://numpy.org/doc/stable/user/absolute_beginners.html

## Basics

In [1]:
import numpy as np  # convention

An array is a central data structure of the NumPy library. An array is a grid of values and it contains information about the raw data, how to locate an element, and how to interpret an element. It has a grid of elements that can be indexed in various ways. The elements are all of the same type, referred to as the array **dtype**.

An array can be indexed by a tuple of nonnegative integers, by booleans, by another array, or by integers. The rank of the array is the number of dimensions. The shape of the array is a tuple of integers giving the size of the array along each dimension.

One way we can initialize NumPy arrays is from Python lists, using nested lists for two- or higher-dimensional data.

We can access the elements in the array using square brackets. When you’re accessing elements, remember that indexing in NumPy starts at 0. That means that if you want to access the first element in your array, you’ll be accessing element “0”.

In [ ]:
a = np.array([1, 2, 3, 4, 5, 6])
print(a[0])
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(a[0])

You might occasionally hear an array referred to as a “ndarray,” which is shorthand for “N-dimensional array.” An N-dimensional array is simply an array with any number of dimensions. You might also hear 1-D, or one-dimensional array, 2-D, or two-dimensional array, and so on. The NumPy ndarray class is used to represent both matrices and vectors. A vector is an array with a single dimension (there’s no difference between row and column vectors), while a matrix refers to an array with two dimensions. For 3-D or higher dimensional arrays, the term tensor is also commonly used.



### What are the attributes of an array?

An array is usually a fixed-size container of items of the same type and size. The number of dimensions and items in an array is defined by its shape. The shape of an array is a tuple of non-negative integers that specify the sizes of each dimension.

In NumPy, dimensions are called axes. This means that if you have a 2D array that looks like this:


In [ ]:
a = np.array(
    [[0., 0., 0.],
     [1., 1., 1.]]
    )
a

Your array has 2 axes. The first axis has a length of 2 and the second axis has a length of 3.

Just like in other Python container objects, the contents of an array can be accessed and modified by indexing or slicing the array. Unlike the typical container objects, different arrays can share the same data, so changes made on one array might be visible in another.

Array attributes reflect information intrinsic to the array itself. If you need to get, or even set, properties of an array without creating a new array, you can often access an array through its attributes.

`ndarray.ndim` will tell you the number of axes, or dimensions, of the array.

`ndarray.size` will tell you the total number of elements of the array. This is the product of the elements of the array’s shape.

`ndarray.shape` will display a tuple of integers that indicate the number of elements stored along each dimension of the array. If, for example, you have a 2-D array with 2 rows and 3 columns, the shape of your array is (2, 3).

In [ ]:
print(a.ndim)
print(a.size)
print(a.shape)

### Create basic array
To create a NumPy array, you can use the function `np.array()`.

All you need to do to create a simple array is pass a list to it. If you choose to, you can also specify the type of data in your list.

In [ ]:
a = np.array([1, 2, 3])

Besides creating an array from a sequence of elements, you can easily create an array filled with 0’s:

In [ ]:
np.zeros(2)

Or an array filled with 1’s:

In [ ]:
np.ones(2)

Or even an empty array! The function empty creates an array whose initial content is random and depends on the state of the memory. The reason to use empty over zeros (or something similar) is speed - just make sure to fill every element afterwards!

In [ ]:
np.empty(2)

You can create an array with a range of elements (similar to Python's range() function):

In [ ]:
np.arange(4)

And even an array that contains a range of evenly spaced intervals. To do this, you will specify the first number, last number, and the step size.

In [ ]:
np.arange(2, 9, 2)

You can also use `np.linspace()` to create an array with values that are spaced linearly in a specified interval:

In [ ]:
np.linspace(0, 10, num=5)

While the default data type is floating point (`np.float64`), you can explicitly specify which data type you want using the dtype keyword.

In [ ]:
x = np.ones(2, dtype=np.int64)
x

### Why not using a Python list?
NumPy gives you an enormous range of fast and efficient ways of creating arrays and manipulating numerical data inside them. While a Python list can contain different data types within a single list, all of the elements in a NumPy array should be homogeneous. The mathematical operations that are meant to be performed on arrays would be extremely inefficient if the arrays weren’t homogeneous.
NumPy arrays are faster and more compact than Python lists. An array consumes less memory and is convenient to use. NumPy uses much less memory to store data and it provides a mechanism of specifying the data types. This allows the code to be optimized even further.

In [ ]:
# multiply all elements in a list/array by k
def scalar_py_slow(l, k):
  multiplied = []
  for x in l:
    multiplied.append(x * k)
  return multiplied

def scalar_py_fast(l, k):
  return [x * k for x in l]

def scalar_numpy(a, k):
  return a * k

In [ ]:
l = list(range(100000))
%timeit scalar_py_slow(l, 10)

In [ ]:
%timeit scalar_py_fast(l, 10)

In [ ]:
a = np.array(l)
%timeit scalar_numpy(a, 10)

In [ ]:
import sys
f"Memory occupation: list = {sys.getsizeof(l)//1e3} KB, array = {sys.getsizeof(a)//1e3} KB"

### Reshaping
Using `arr.reshape()` will give a new shape to an array without changing the data. Just remember that when you use the reshape method, the array you want to produce needs to have the same number of elements as the original array. If you start with an array with 12 elements, you’ll need to make sure that your new array also has a total of 12 elements. For example, you can reshape a 6-elements array to an array with three rows and two columns:

In [ ]:
a = np.arange(6)
print(f"before reshaping, array:\n{a} \nwith shape {a.shape}\n")
a = a.reshape(3, 2)
print(f"after reshaping, array:\n{a} \nwith shape {a.shape}")

### Indexing and slicing
You can index and slice NumPy arrays in the same ways you can slice Python lists. Slices of an array are implemented as **views**, **not copies**, on the original data, sharing the same memory.

In [ ]:
data = np.array([1, 2, 3, 4, 5])
print(data[1])
print(data[0:2])
print(data[1:])
print(data[-2:])

You may want to take a section of your array or specific array elements to use in further analysis or additional operations. To do that, you’ll need to subset, slice, and/or index your arrays.

If you want to select values from your array that fulfill certain conditions, it’s straightforward with NumPy.

For example, given an array we can easily print all values less than 5:

In [ ]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

In [ ]:
# this is called fancy indexing
a[a < 5]

You can also select, for example, numbers that are equal to or greater than 5, and use that condition to index an array.

In [ ]:
five_up = (a >= 5)
five_up

In [ ]:
a[five_up]

You can select elements that are divisible by 2:

In [ ]:
a[a % 2 == 0]

Or you can select elements that satisfy two conditions using the & and | operators:

In [ ]:
a[(a > 2) & (a < 11)]

Elementary operations between arrays are also supported:

In [ ]:
a = np.ones(5)
b = np.ones(5)
a + b  # elementwise sum

In [ ]:
a * b # elementwise product

In [ ]:
a * 5.5 # multiply all elements by a single value

Take care about shapes, as arrays must be *broadcastable* to carry out these operations. For example, we can add a (3, 4) array to a (3, 1) array:

In [ ]:
a = np.ones((3, 4))
b = np.ones((3, 1))
print(f"a shape: {a.shape}, b shape: {b.shape}\n")
c = a + b
print(f"a + b shape: {c.shape}\nresult is: \n{c}")

For more info: https://numpy.org/doc/stable/user/basics.broadcasting.html or see below (it's not trivial, I know)

## Mathematical and statistical functions

Numpy offers many common mathematical functions out of the box. See https://numpy.org/doc/stable/reference/routines.math.html for more information.

Let's test `exp()` (exponential) and `maximum()` (element-wise maximum of two arrays).

In [ ]:
a = np.array([[1.,2.,3.], [4.,5.,6.]])
b = np.array([[3.,3.,7.], [1.,1.,2.]])

print("exp function")
print(np.exp(a))
print()

print("element-wise maximum")
print(np.maximum(a, b))

Typical aggregation and statistical functions such as `sum`, `mean`, `var` are also available.

In case of matrices, it is possible to specify the **direction** (*axis*) of the operation.

In [ ]:
m = np.array([[1.,2.,3.],
              [4.,5.,6.]])

print(m)
print()

print("No direction/axis")
print(np.mean(m))
print()

print("mean over axis 0 (across rows)")
print(np.mean(m, axis=0))
print()

print("mean over axis 1 (across cols)")
print(np.mean(m, axis=1))
print()

In [2]:
def pysum(l):
  return sum(l)
def numpysum(a):
  return a.sum()
l = list(range(1000000))
%timeit pysum(l)
a = np.array(l)
%timeit numpysum(a)

21 ms ± 1.19 ms per loop (mean ± std. dev. of 7 runs, 100 loops each)
221 µs ± 7.92 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


Similarly to standard Python, the `sort` method can be used to sort an array or to get a sorted copy.

There is no `key` parameter.

See https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.sort.html.

In [ ]:
data = np.array([1,-2,3,-4,5])

s = np.sort(data)
print("sorted copy    ", s)
print("original data  ", data)
print()

data.sort()
print("after data.sort()")
print("original data  ", data)

Also sorting may have a direction.

In [ ]:
m = np.array([[3., 5.,2.], [6., 1.,5.]])

print(m, '\n')

print("sort over axis 0 (across rows)")
print(np.sort(m, axis=0), '\n')

print("sort over axis 1 (across cols)")
print(np.sort(m, axis=1), '\n')

print("flatten and then sort")
print(np.sort(m, axis=None))

[[3. 5. 2.]
 [6. 1. 5.]] 

sort over axis 0 (across rows)
[[3. 1. 2.]
 [6. 5. 5.]] 

sort over axis 1 (across cols)
[[2. 3. 5.]
 [1. 5. 6.]] 

flatten and then sort
[1. 2. 3. 5. 5. 6.]


A useful method is `argsort`, which returns the positions of the elements in sorted order, withouth modifying the original array.

The output of `argsort`, can be used in conjuction with fancy indexing.

Example: sort by income and print the corresponding name.

In [ ]:
names = np.array(['Mark', 'Joe', 'Will', 'Bob', 'Jane', 'Carol', 'Donald'])
salaries = np.array([2000,   1200,  3000,  2100,   1580,   1700,    900])

sorted_pos = np.argsort(salaries)
print("sorted positions", sorted_pos)

print("ages", names[sorted_pos]) # This is called fancy indexing!

## Optimization

Find the root of a function given it first derivative.

See https://docs.scipy.org/doc/scipy/reference/optimize.html

In [3]:
from scipy import optimize
def f(x):
    return (x**3 - 1)  # only one real root at x = 1

def fprime(x):
    return 3*x**2

sol = optimize.root_scalar( f,                # function
                            x0=0.2,           # initial guess
                            fprime=fprime,    # first derivative
                            method='newton')  # optimization method

print(f"The root of the function is: {sol.root}")

The root of the function is: 1.0


Find the minimum of a function.

In [11]:
def f(x):
    return (x ** 2 - 2 * x - 1)

sol = optimize.minimize_scalar(f)
print(f"The minimum of the function is: {sol.x}")

The minimum of the function is: 1.0


# More Numpy ?

NumPy deserves your interest, especially for implementing numerical algorithms, matrix-based operations, and to exploit its great algorithms (see also scipy).

From a data perspective, it provides a low level access. We will see the Pandas library, which is more data-oriented and it shares several commonalities with NumPy.

### Arrays

An array object represents a multidimensional, homogeneous array of items of the same data-type. Numpy array can be accessed by index into square brackets.

In [ ]:
# Creating a rank 1 array
a = np.array([1, 2, 3])  
print(type(a), a.shape, a[0], a[1], a[2])

In [ ]:
# Changing an element of the array
a[0] = 5                 
print(a) 

In [ ]:
# Create a rank 2 array
b = np.array([[1, 2, 3], [4, 5, 6]])
print(b)

In [ ]:
print(b.shape)

In [ ]:
print(b[0, 0], b[0, 1], b[1, 0])

Numpy have methods to create several defaults arrays

In [ ]:
# Create an array of all zeros
print("Zeros array")
a = np.zeros((2,2))  
print(a)

In [ ]:
print("Ones array")
b = np.ones((1,2))   # Create an array of all ones
print(b)

In [ ]:
print("Full array")
c = np.full((2,2), 7) # Create an array of constants (7)
print(c)

In [ ]:
print("Identity matrix")
d = np.eye(2)        # Create a 2x2 identity matrix
print(d)

In [ ]:
print("Random matrix")
e = np.random.random((2,2)) # Create an array filled with random values
print(e)

All the items of a numpy array have the same type. When you create an array, numpy guess which datatype fix better to your data, but you can set it when creating the numpy array. 

In [ ]:
a = np.array([1, 2])                   # Let numpy choose the datatype
b = np.array([1.0, 2.0])               # Let numpy choose the datatype
c = np.array([1, 2], dtype=np.float32) #Force a particular datatype
d = np.array([1, 2], dtype=np.int64)   #Force a particular datatype
print(a)
print(b)
print(c)
print(d)

Numpy offers several ways to index into arrays.
Similar to lists numpy arrays can be **sliced** specifing a slice for each dimension of the array.

In [ ]:
import numpy as np
a = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8], 
              [9, 10, 11, 12]])

b = a[:2, 1:3] # rows 0,1 and columns 1,2
print(b)

A slice of an array share the same memory area of the original array. Modifing it will modify also the original array

In [ ]:
b[0, 0] = 100
print(a[0,1])

Integer arrays can be used as indexes of other arrays

In [ ]:
# Create an array of indices
b = np.array([0, 2, 0])
# Select one element from each row of a using the indices in b
print(a[np.arange(3), b])  # a[[0,1,2], [0,2,0]] ->  Prints a[0,0] , a[1,2], a[2,0]

Boolean array indexing: Boolean array indexing lets you pick out arbitrary elements of an array. Frequently this type of indexing is used to select the elements of an array that satisfies some condition. Here is an example:

In [ ]:
import numpy as np

a = np.array([[1,2], [3, 4], [5, 6]])

idx = (a > 2)  # Find the elements of a that are bigger than 2;
                    # this returns a numpy array of Booleans of the same
                    # shape as a, where each slot of bool_idx tells
                    # whether that element of a is > 2.
print(a)
print(idx)

In [ ]:
print(a[idx])

### Array math

Basic mathematical functions operate elementwise on arrays, and are available both as operator overloads and as functions in the numpy module:

In [ ]:
import numpy as np

x = np.array([[-1,-2],[-3,-4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

print("x=\n", x)
print("y=\n",y)

In [ ]:
print("Element-wise sum")
print(x + y)

In [ ]:
print("Element-wise difference")
print(x - y)

In [ ]:
print("Element-wise product")
print(x * y)

In [ ]:
print("Element-wise division")
print(x / y)

In [ ]:
print("Element-wise absoulte value")
print(np.abs(x))

Moreover, several mathematical operation between arrays are implemented in Numpy.

In [ ]:
print("Elementwise square root")
print(np.sqrt(y))

In [ ]:
print("Dot product")
print(x.dot(y))
print(np.dot(x, y))

Numpy provides several reduction functions.

In [ ]:
# Compute sum of all elements; prints "10"
print(np.sum(x))

In [ ]:
# Compute sum of each column; prints "[-4 -6]"
print(np.sum(x, axis=0))

In [ ]:
 # Compute sum of each row; prints "[-3 -7]"
print(np.sum(x, axis=1))

In [ ]:
# Compute the mean of all elements
print(np.mean(x))

In [ ]:
# Compute the mean of axis 0
print(np.mean(x, axis= 0))

In [ ]:
# Compute the mean of axis 1
print(np.mean(x, axis=1))

Moreover, Numpy provides function to modify the shape of arrays.

In [ ]:
print(x)
print("Transpose")
print(x.T)

In [ ]:
print("Reshape Shape source: ", x.shape, "Shape target: ", (1,4))
print(x.reshape([1,4]))

You can find the full list functions provided by numpy in the [documentation](https://docs.scipy.org/doc/numpy-1.17.0/reference/).

### Broadcasting

Broadcasting is the mechanism used by numpy to deal with arrays of different shapes during mathematical operations. This can be extremely useful in a variety of situation and expedites the computation time in matrix operations. Below an example of sum between arrays with different shapes implemented with for cycle and without broadcasting: 

In [ ]:
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([0, 0, 1])

print("x=\n",x , "Shape: ", x.shape)
print("v=\n", v, "Shape: ", v.shape)

**x + v Cycling rows**

In [ ]:
# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
y = np.empty_like(x)   # Create an empty matrix with the same shape as x

# Add the vector v to each row of the matrix x with an explicit loop
for i in range(4):
    y[i, :] = x[i, :] + v

print(y)

If the matrix _x_ is very large, computing loop cycles in Python is really slow. 
Another way to implement the same problem improving the perfomances could be stacking  multiple copies of v.

**x+v Stacking**

In [ ]:
print("x= \n", x)
vv = np.tile(v, (4, 1))  # Stack 4 copies of v on top of each other
print("vv = \n", vv)
y = x + vv
print("x + vv =\n" , y)

This version is computationally cheap but the code is not straightforward to write. Broadcasting allows to do it extremely easy automatically adressing shape compability problems.

**x+v Numpy Broadcasting*

In [ ]:
# Add v to each row of x using broadcasting
y = x + v  
print(y)

The line `y = x + v` works even though `x` has shape `(4, 3)` and `v` has shape `(3,)` due to broadcasting; this line works as if v actually had shape `(4, 3)`, where each row was a copy of `v`, and the sum was performed elementwise.

Example: multiply by a scalar:

In [ ]:
# Multiply a matrix by a constant:
# x has shape (2, 3). Numpy treats scalars as arrays of shape () these can be broadcast together to shape (2, 3)
print(x * 2)

**Broadcasting** two arrays together follows these **rules**:

1. If the arrays do not have the same rank, prepend the shape of the lower rank array with 1s until both shapes have the same length.
2. The two arrays are said to be compatible in a dimension if they have the same size in the dimension, or if one of the arrays has size 1 in that dimension.
3. The arrays can be broadcast together if they are compatible in all dimensions.
4. After broadcasting, each array behaves as if it had shape equal to the elementwise maximum of shapes of the two input arrays.
5. In any dimension where one array had size 1 and the other array had size greater than 1, the first array behaves as if it were copied along that dimension

Example of **compatible shapes** for broadcasting: 

A      (3d array):  15 x 3 x 5

B      (2d array):       3 x 5

**Result** (3d array):  15 x 3 x 5

A      (3d array):  15 x 3 x 5

B      (3d array):  15 x 1 x 5

**Result** (3d array):  15 x 3 x 5

A      (2d array):  5 x 4

B      (1d array):      1

**Result** (2d array):  5 x 4

Example of **incompatible shapes** for broadcasting:

A      (1d array):  3

B      (1d array):  4

**Trailing dimensions do not match**

In [ ]:
a=np.array([1,2,3])
b=np.array([1,2,3,4])
print(a+b) # Throw Exception